version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - MODEL_PATH=/app/models/best_model.pkl
    depends_on:
      - train

  train:
    build: .
    command: bash -c "pip install dvc && dvc repro"
    volumes:
      - .:/app
