# stages:
#   preprocess:
#     cmd: python src/preprocessing/preprocess.py
#     deps:
#       - ../data/raw/weather.csv
#     outs:
#       - ../data/processed/train_X.csv
#       - ../data/processed/test_X.csv
#       - ../data/processed/train_y.csv
#       - ../data/processed/test_y.csv
#   train:
#     cmd: python src/training/train.py
#     deps:
#       - ../data/processed/train_X.csv
#       - ../data/processed/train_y.csv
#       - src/models/model.py
#     outs:
#       - ../models/model.pkl
#   tune:
#     cmd: python scripts/hp_tuning.py
#     deps:
#       - ../data/processed/train_X.csv
#       - ../data/processed/train_y.csv
#       - hp_config.json
#     outs:
#       - ../models/best_model.pkl
#   evaluate:
#     cmd: python src/evaluation/evaluate.py
#     deps:
#       - ../data/processed/test_X.csv
#       - ../data/processed/test_y.csv
#       - ../models/best_model.pkl
#     outs:
#       - ../reports/metrics.json
#       - ../reports/confusion_matrix.png



stages:
  preprocess:
    cmd: python preprocess_dataset.py
    deps:
    - preprocess_dataset.py
    - raw_dataset/weather.csv
    - utils_and_constants.py
    outs:
    - processed_dataset/weather.csv
  hp_tune:
    cmd: python hp_tuning.py
    deps:
    - processed_dataset/weather.csv
    - hp_config.json
    - hp_tuning.py
    - utils_and_constants.py
    outs:
      - hp_tuning_results.md:
          cache: false
  train:
    cmd: python train.py
    deps:
    - metrics_and_plots.py
    - model.py
    - processed_dataset/weather.csv
    - rfc_best_params.json
    - train.py
    - utils_and_constants.py
    metrics:
      - metrics.json:
          cache: false
    plots:
    - predictions.csv:
        template: confusion
        x: predicted_label
        y: true_label
        x_label: 'Predicted label'
        y_label: 'True label'
        title: Confusion matrix
        cache: false
    - roc_curve.csv:
        template: simple
        x: fpr
        y: tpr
        x_label: 'False Positive Rate'
        y_label: 'True Positive Rate'
        title: ROC curve
        cache: false